import Config

# Configure your database
config :financial_advisor_agent, FinancialAdvisorAgent.Repo,
  username: System.get_env("DB_USERNAME") || "postgres",
  password: System.get_env("DB_PASSWORD") || "postgres",
  hostname: System.get_env("DB_HOSTNAME") || "localhost",
  database: System.get_env("DB_DATABASE") || "financial_advisor_agent_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :financial_advisor_agent, FinancialAdvisorAgentWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "3YnjUOTCI63m06VgQmWPD1orEbISHfjksMP1kj3Jvtypn2kXQD2q6AkMeJz0OR1a",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:financial_advisor_agent, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:financial_advisor_agent, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :financial_advisor_agent, FinancialAdvisorAgentWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/financial_advisor_agent_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :financial_advisor_agent, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Development Environment Configuration
# Use mock services and dummy values for development

# OpenAI Configuration - Use environment variable
config :financial_advisor_agent, :openai,
  api_key: System.get_env("OPENAI_API_KEY") || "your_openai_api_key_here",
  use_mock: false

# HubSpot Configuration - Use real API key in development
config :financial_advisor_agent, :hubspot,
  client_id: System.get_env("HUBSPOT_CLIENT_ID") || "mock-client-id",
  client_secret: System.get_env("HUBSPOT_CLIENT_SECRET") || "mock-client-secret",
  api_key: System.get_env("HUBSPOT_API_KEY") || "your_hubspot_api_key_here",
  redirect_uri: System.get_env("HUBSPOT_REDIRECT_URI") || "http://localhost:4000/hubspot/callback",
  use_mock: false

# Google OAuth Configuration - Use real credentials
config :ueberauth, Ueberauth,
  providers: [
    google: {Ueberauth.Strategy.Google, [
      default_scope: "email profile https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events",
      client_id: System.get_env("GOOGLE_CLIENT_ID") || "your_google_client_id_here",
      client_secret: System.get_env("GOOGLE_CLIENT_SECRET") || "your_google_client_secret_here"
    ]}
  ]

# Guardian Configuration - Use dummy secret in development
config :financial_advisor_agent, FinancialAdvisorAgent.Guardian,
  issuer: "FinancialAdvisorAgent",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY") || "mock-guardian-secret-key-for-development-only"

# Enable real services for OpenAI and Google OAuth in development
config :financial_advisor_agent, :external_services,
  use_mocks: false,
  mock_mode: :development,
  use_real_google_oauth: true
