import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :financial_advisor_agent, FinancialAdvisorAgentWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Production Environment Configuration
# Use real services with production settings

# OpenAI Configuration - Real API key required
config :financial_advisor_agent, :openai,
  api_key: System.get_env("OPENAI_API_KEY"),
  use_mock: false

# HubSpot Configuration - Real credentials required
config :financial_advisor_agent, :hubspot,
  client_id: System.get_env("HUBSPOT_CLIENT_ID"),
  client_secret: System.get_env("HUBSPOT_CLIENT_SECRET"),
  redirect_uri: System.get_env("HUBSPOT_REDIRECT_URI"),
  use_mock: false

# Google OAuth Configuration - Real credentials required
config :ueberauth, Ueberauth,
  providers: [
    google: {Ueberauth.Strategy.Google, [
      default_scope: "email profile https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events",
      client_id: System.get_env("GOOGLE_CLIENT_ID"),
      client_secret: System.get_env("GOOGLE_CLIENT_SECRET")
    ]}
  ]

# Guardian Configuration - Real secret required
config :financial_advisor_agent, FinancialAdvisorAgent.Guardian,
  issuer: "FinancialAdvisorAgent",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

# Disable mock mode for production
config :financial_advisor_agent, :external_services,
  use_mocks: false,
  mock_mode: :production

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
